spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cinema?characterEncoding=UTF-8
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: com.cinema.core.config.MySQL8DialectCustom  # 커스텀 한거 적용
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
  #        generate_statistics: true # spring.data metric 활성화
  sql:
    init:
      mode: never
